name: Deploy
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      API_HOST: https://matapi.messenger.fridaysforfuture.dev
      SSR: false
      BASE_PATH: "/matapp-app/"
      TARGET: static
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.5.1
        with:
          node-version: 16.x
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install
      - name: Generate static files
        run: yarn run generate
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
